[project]
name = "is-even"
version = "1.0.0"
description = ""
authors = [
    {name = "Chris Lovering", email = "chris.lovering.95@gmail.com"}
]
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "fastapi==0.117.1",
    "uvicorn[standard]==0.37.0"
]
